# ----
# Site

environment: build
baseurl: .
permalink: /:title.html

collections:
  docs:
    title: Documentation
    permalink: /:title.html
    output: true

sass:
  load_paths:
    - _sass
    - node_modules/bootstrap/scss
